/**
 * Regenerates lib/logos.ts from the simple-icons package.
 *
 *   node scripts/generate-logos.mjs
 *
 * Only entries that are actual products get a logo. Concepts — Observability,
 * CAP Theorem, Idempotency, RAG, Design Tokens — have no trademark and keep
 * their emoji glyph, which is the honest distinction and a useful visual one.
 *
 * The path data is CC0-1.0 (simple-icons' own licence). The marks themselves
 * remain trademarks of their respective owners and are used here nominatively,
 * to refer to the products they identify.
 */
import { writeFileSync } from "node:fs";
import * as simpleIcons from "simple-icons";

/** entry id in lib/entries.ts → simple-icons slug */
const wanted = {
  docker: "docker",
  kubernetes: "kubernetes",
  terraform: "terraform",
  kafka: "apachekafka",
  postgresql: "postgresql",
  redis: "redis",
  nginx: "nginx",
  flask: "flask",
  fastapi: "fastapi",
  react: "react",
  nextjs: "nextdotjs",
  figma: "figma",
};

const records = Object.entries(wanted).map(([entryId, slug]) => {
  const key = `si${slug.charAt(0).toUpperCase()}${slug.slice(1)}`;
  const icon = simpleIcons[key];
  if (!icon) throw new Error(`simple-icons has no "${slug}" (looked for ${key})`);
  return { entryId, slug, title: icon.title, hex: icon.hex, path: icon.path };
});

const body = records
  .map(
    ({ entryId, slug, title, hex, path }) =>
      `  "${entryId}": {\n` +
      `    slug: ${JSON.stringify(slug)},\n` +
      `    title: ${JSON.stringify(title)},\n` +
      `    hex: ${JSON.stringify(`#${hex}`)},\n` +
      `    path: ${JSON.stringify(path)},\n` +
      `  },`,
  )
  .join("\n");

const file = `// Generated by scripts/generate-logos.mjs — do not edit by hand.
// Run \`node scripts/generate-logos.mjs\` after changing the list in that script.
//
// Path data comes from simple-icons (CC0-1.0). The marks themselves remain
// trademarks of their respective owners and appear here nominatively, to refer
// to the products they identify.

export type Logo = {
  /** simple-icons slug, kept for regeneration. */
  slug: string;
  /** Official product name, used as the accessible label. */
  title: string;
  /** Official brand colour. */
  hex: string;
  /** Single path, 24x24 viewBox. */
  path: string;
};

/** Keyed by entry id. Concepts are absent on purpose — they have no logo. */
export const logos: Record<string, Logo> = {
${body}
};

export function getLogo(entryId: string): Logo | undefined {
  return logos[entryId];
}
`;

writeFileSync(new URL("../lib/logos.ts", import.meta.url), file);
console.log(`Wrote lib/logos.ts with ${records.length} logos.`);
